// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	tenantmodel "github.com/chaitanya-bhagat/knowledge-nexus/internals/tenant/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetMembership mocks base method.
func (m *MockReader) GetMembership(ctx context.Context, tenantID, userID uuid.UUID) (tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, tenantID, userID)
	ret0, _ := ret[0].(tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockReaderMockRecorder) GetMembership(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockReader)(nil).GetMembership), ctx, tenantID, userID)
}

// ListMemberships mocks base method.
func (m *MockReader) ListMemberships(ctx context.Context, tenantID uuid.UUID) ([]tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", ctx, tenantID)
	ret0, _ := ret[0].([]tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockReaderMockRecorder) ListMemberships(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockReader)(nil).ListMemberships), ctx, tenantID)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// CreateMembership mocks base method.
func (m *MockWriter) CreateMembership(ctx context.Context, membership *tenantmodel.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockWriterMockRecorder) CreateMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockWriter)(nil).CreateMembership), ctx, membership)
}

// UpdateMembershipRole mocks base method.
func (m *MockWriter) UpdateMembershipRole(ctx context.Context, tenantID, userID uuid.UUID, role tenantmodel.Role, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipRole", ctx, tenantID, userID, role, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipRole indicates an expected call of UpdateMembershipRole.
func (mr *MockWriterMockRecorder) UpdateMembershipRole(ctx, tenantID, userID, role, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipRole", reflect.TypeOf((*MockWriter)(nil).UpdateMembershipRole), ctx, tenantID, userID, role, updatedAt)
}

// UpdateMembershipStatus mocks base method.
func (m *MockWriter) UpdateMembershipStatus(ctx context.Context, tenantID, userID uuid.UUID, status tenantmodel.MembershipStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipStatus", ctx, tenantID, userID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipStatus indicates an expected call of UpdateMembershipStatus.
func (mr *MockWriterMockRecorder) UpdateMembershipStatus(ctx, tenantID, userID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipStatus", reflect.TypeOf((*MockWriter)(nil).UpdateMembershipStatus), ctx, tenantID, userID, status, updatedAt)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateMembership mocks base method.
func (m *MockRepository) CreateMembership(ctx context.Context, membership *tenantmodel.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockRepositoryMockRecorder) CreateMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockRepository)(nil).CreateMembership), ctx, membership)
}

// GetMembership mocks base method.
func (m *MockRepository) GetMembership(ctx context.Context, tenantID, userID uuid.UUID) (tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, tenantID, userID)
	ret0, _ := ret[0].(tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockRepositoryMockRecorder) GetMembership(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockRepository)(nil).GetMembership), ctx, tenantID, userID)
}

// ListMemberships mocks base method.
func (m *MockRepository) ListMemberships(ctx context.Context, tenantID uuid.UUID) ([]tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", ctx, tenantID)
	ret0, _ := ret[0].([]tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockRepositoryMockRecorder) ListMemberships(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockRepository)(nil).ListMemberships), ctx, tenantID)
}

// UpdateMembershipRole mocks base method.
func (m *MockRepository) UpdateMembershipRole(ctx context.Context, tenantID, userID uuid.UUID, role tenantmodel.Role, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipRole", ctx, tenantID, userID, role, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipRole indicates an expected call of UpdateMembershipRole.
func (mr *MockRepositoryMockRecorder) UpdateMembershipRole(ctx, tenantID, userID, role, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipRole", reflect.TypeOf((*MockRepository)(nil).UpdateMembershipRole), ctx, tenantID, userID, role, updatedAt)
}

// UpdateMembershipStatus mocks base method.
func (m *MockRepository) UpdateMembershipStatus(ctx context.Context, tenantID, userID uuid.UUID, status tenantmodel.MembershipStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipStatus", ctx, tenantID, userID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipStatus indicates an expected call of UpdateMembershipStatus.
func (mr *MockRepositoryMockRecorder) UpdateMembershipStatus(ctx, tenantID, userID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipStatus", reflect.TypeOf((*MockRepository)(nil).UpdateMembershipStatus), ctx, tenantID, userID, status, updatedAt)
}
