// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	kbmodel "github.com/chaitanya-bhagat/knowledge-nexus/internals/knowledgebase/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetKnowledgeBaseByID mocks base method.
func (m *MockReader) GetKnowledgeBaseByID(ctx context.Context, kbID, tenantID uuid.UUID) (kbmodel.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBaseByID", ctx, kbID, tenantID)
	ret0, _ := ret[0].(kbmodel.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBaseByID indicates an expected call of GetKnowledgeBaseByID.
func (mr *MockReaderMockRecorder) GetKnowledgeBaseByID(ctx, kbID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBaseByID", reflect.TypeOf((*MockReader)(nil).GetKnowledgeBaseByID), ctx, kbID, tenantID)
}

// ListKnowledgeBasesByTenantID mocks base method.
func (m *MockReader) ListKnowledgeBasesByTenantID(ctx context.Context, tenantID uuid.UUID) ([]kbmodel.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBasesByTenantID", ctx, tenantID)
	ret0, _ := ret[0].([]kbmodel.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBasesByTenantID indicates an expected call of ListKnowledgeBasesByTenantID.
func (mr *MockReaderMockRecorder) ListKnowledgeBasesByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBasesByTenantID", reflect.TypeOf((*MockReader)(nil).ListKnowledgeBasesByTenantID), ctx, tenantID)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// CreateKnowledgeBase mocks base method.
func (m *MockWriter) CreateKnowledgeBase(ctx context.Context, kb kbmodel.KnowledgeBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", ctx, kb)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockWriterMockRecorder) CreateKnowledgeBase(ctx, kb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockWriter)(nil).CreateKnowledgeBase), ctx, kb)
}

// UpdateKnowledgeBase mocks base method.
func (m *MockWriter) UpdateKnowledgeBase(ctx context.Context, kb *kbmodel.KnowledgeBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", ctx, kb)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockWriterMockRecorder) UpdateKnowledgeBase(ctx, kb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockWriter)(nil).UpdateKnowledgeBase), ctx, kb)
}

// UpdateKnowledgeBaseStatus mocks base method.
func (m *MockWriter) UpdateKnowledgeBaseStatus(ctx context.Context, tenantID, kbID uuid.UUID, status kbmodel.Status, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBaseStatus", ctx, tenantID, kbID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnowledgeBaseStatus indicates an expected call of UpdateKnowledgeBaseStatus.
func (mr *MockWriterMockRecorder) UpdateKnowledgeBaseStatus(ctx, tenantID, kbID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBaseStatus", reflect.TypeOf((*MockWriter)(nil).UpdateKnowledgeBaseStatus), ctx, tenantID, kbID, status, updatedAt)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateKnowledgeBase mocks base method.
func (m *MockRepository) CreateKnowledgeBase(ctx context.Context, kb kbmodel.KnowledgeBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", ctx, kb)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockRepositoryMockRecorder) CreateKnowledgeBase(ctx, kb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockRepository)(nil).CreateKnowledgeBase), ctx, kb)
}

// GetKnowledgeBaseByID mocks base method.
func (m *MockRepository) GetKnowledgeBaseByID(ctx context.Context, kbID, tenantID uuid.UUID) (kbmodel.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBaseByID", ctx, kbID, tenantID)
	ret0, _ := ret[0].(kbmodel.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBaseByID indicates an expected call of GetKnowledgeBaseByID.
func (mr *MockRepositoryMockRecorder) GetKnowledgeBaseByID(ctx, kbID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBaseByID", reflect.TypeOf((*MockRepository)(nil).GetKnowledgeBaseByID), ctx, kbID, tenantID)
}

// ListKnowledgeBasesByTenantID mocks base method.
func (m *MockRepository) ListKnowledgeBasesByTenantID(ctx context.Context, tenantID uuid.UUID) ([]kbmodel.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBasesByTenantID", ctx, tenantID)
	ret0, _ := ret[0].([]kbmodel.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBasesByTenantID indicates an expected call of ListKnowledgeBasesByTenantID.
func (mr *MockRepositoryMockRecorder) ListKnowledgeBasesByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBasesByTenantID", reflect.TypeOf((*MockRepository)(nil).ListKnowledgeBasesByTenantID), ctx, tenantID)
}

// UpdateKnowledgeBase mocks base method.
func (m *MockRepository) UpdateKnowledgeBase(ctx context.Context, kb *kbmodel.KnowledgeBase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", ctx, kb)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockRepositoryMockRecorder) UpdateKnowledgeBase(ctx, kb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockRepository)(nil).UpdateKnowledgeBase), ctx, kb)
}

// UpdateKnowledgeBaseStatus mocks base method.
func (m *MockRepository) UpdateKnowledgeBaseStatus(ctx context.Context, tenantID, kbID uuid.UUID, status kbmodel.Status, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBaseStatus", ctx, tenantID, kbID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnowledgeBaseStatus indicates an expected call of UpdateKnowledgeBaseStatus.
func (mr *MockRepositoryMockRecorder) UpdateKnowledgeBaseStatus(ctx, tenantID, kbID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBaseStatus", reflect.TypeOf((*MockRepository)(nil).UpdateKnowledgeBaseStatus), ctx, tenantID, kbID, status, updatedAt)
}
