// Code generated by MockGen. DO NOT EDIT.
// Source: membership_repository.go
//
// Generated by this command:
//
//	mockgen -source=membership_repository.go -destination=mocks/membership_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	tenantmodel "github.com/chaitanya-bhagat/knowledge-nexus/internals/tenant/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRepository is a mock of MembershipRepository interface.
type MockMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockMembershipRepositoryMockRecorder is the mock recorder for MockMembershipRepository.
type MockMembershipRepositoryMockRecorder struct {
	mock *MockMembershipRepository
}

// NewMockMembershipRepository creates a new mock instance.
func NewMockMembershipRepository(ctrl *gomock.Controller) *MockMembershipRepository {
	mock := &MockMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepository) EXPECT() *MockMembershipRepositoryMockRecorder {
	return m.recorder
}

// CreateMembership mocks base method.
func (m *MockMembershipRepository) CreateMembership(ctx context.Context, membership *tenantmodel.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMembership indicates an expected call of CreateMembership.
func (mr *MockMembershipRepositoryMockRecorder) CreateMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMembership", reflect.TypeOf((*MockMembershipRepository)(nil).CreateMembership), ctx, membership)
}

// GetMembership mocks base method.
func (m *MockMembershipRepository) GetMembership(ctx context.Context, tenantID, userID uuid.UUID) (tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, tenantID, userID)
	ret0, _ := ret[0].(tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockMembershipRepositoryMockRecorder) GetMembership(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockMembershipRepository)(nil).GetMembership), ctx, tenantID, userID)
}

// ListMemberships mocks base method.
func (m *MockMembershipRepository) ListMemberships(ctx context.Context, tenantID uuid.UUID) ([]tenantmodel.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberships", ctx, tenantID)
	ret0, _ := ret[0].([]tenantmodel.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberships indicates an expected call of ListMemberships.
func (mr *MockMembershipRepositoryMockRecorder) ListMemberships(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberships", reflect.TypeOf((*MockMembershipRepository)(nil).ListMemberships), ctx, tenantID)
}

// UpdateMembershipRole mocks base method.
func (m *MockMembershipRepository) UpdateMembershipRole(ctx context.Context, tenantID, userID uuid.UUID, role tenantmodel.Role, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipRole", ctx, tenantID, userID, role, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipRole indicates an expected call of UpdateMembershipRole.
func (mr *MockMembershipRepositoryMockRecorder) UpdateMembershipRole(ctx, tenantID, userID, role, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipRole", reflect.TypeOf((*MockMembershipRepository)(nil).UpdateMembershipRole), ctx, tenantID, userID, role, updatedAt)
}

// UpdateMembershipStatus mocks base method.
func (m *MockMembershipRepository) UpdateMembershipStatus(ctx context.Context, tenantID, userID uuid.UUID, status tenantmodel.MembershipStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipStatus", ctx, tenantID, userID, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipStatus indicates an expected call of UpdateMembershipStatus.
func (mr *MockMembershipRepositoryMockRecorder) UpdateMembershipStatus(ctx, tenantID, userID, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipStatus", reflect.TypeOf((*MockMembershipRepository)(nil).UpdateMembershipStatus), ctx, tenantID, userID, status, updatedAt)
}
