// Code generated by MockGen. DO NOT EDIT.
// Source: objectstore.go
//
// Generated by this command:
//
//	mockgen -source=objectstore.go -destination=mocks/objectstore_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	storage "github.com/chaitanya-bhagat/knowledge-nexus/internals/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockObjectStore) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStoreMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStore)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockObjectStore) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStore)(nil).Get), ctx, key)
}

// PresignPut mocks base method.
func (m *MockObjectStore) PresignPut(ctx context.Context, key, contentType string, expire time.Duration) (storage.PresignedUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPut", ctx, key, contentType, expire)
	ret0, _ := ret[0].(storage.PresignedUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPut indicates an expected call of PresignPut.
func (mr *MockObjectStoreMockRecorder) PresignPut(ctx, key, contentType, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPut", reflect.TypeOf((*MockObjectStore)(nil).PresignPut), ctx, key, contentType, expire)
}

// Stat mocks base method.
func (m *MockObjectStore) Stat(ctx context.Context, key string) (storage.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, key)
	ret0, _ := ret[0].(storage.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockObjectStoreMockRecorder) Stat(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockObjectStore)(nil).Stat), ctx, key)
}
